### ISSUE TITLE
Text direction: i18n

### ISSUE THREAD

**Issue by airmrcr** [tmplat-extension/tmplat#84]
This was only done for desktop notifications as part of #80 but needs to be applied to the options page and maybe event he popup. Unfortunately, this isn't as easy as it was for the notifications;

``` css
body {
  direction: __MSG_@@bidi_dir__;
}
```

This will work to some extent but much more is required in order to keep the page layout. For the options page at least.
